#!/usr/bin/env node
/* Refuses an edit to one of this repo's three generated mirrors.

   Each one is bytes some script owns, and hand-editing it does not fail at the edit -- it
   fails later, in CI, after the rest of a sweep has already landed on top of it:

     vendor/pristine/**              the three-way merge base a `pull` reads
     vendor/NOTICE.md                generated attribution
     plugins/nt-brand/skills/system/ byte mirror of the published brand-kit

   KEY-DECISION 2026-08-30: Write/Edit only, never Bash. The sanctioned writers
   (`vendor-skills.mjs pull`, `npm run brand:sync`) reach these paths through a shell, and
   fencing Bash would block the very commands this hook tells you to run. The editing tools
   are the surface that has no legitimate reason to touch a mirror.

   KEY-DECISION 2026-08-30: repo-local rather than a plugin hook. These paths exist in this
   repo and nowhere else, so shipping the rule inside nt-dev would carry it to every repo
   that installs the plugin and mean nothing in any of them.

   Config, via `env` in .claude/settings.local.json or the user's:
     NT_MIRROR_FENCE=off   do nothing
*/
import { readFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

if ((process.env.NT_MIRROR_FENCE ?? '').trim().toLowerCase() === 'off') pass();

/* The hook's own location is the repo, so nothing here depends on cwd or on the harness
   naming a project directory. */
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

const FENCED = [
  ['vendor/pristine/', `\`vendor/pristine/\` is the merge base a \`pull\` reads, not a copy of the skill.

Editing it makes the next upstream delta merge against bytes it was never cut from, and
\`node scripts/vendor-skills.mjs verify\` fails in CI. Edit the live skill under
\`plugins/nt-vendor/\` instead; to take an upstream change, run
\`node scripts/vendor-skills.mjs pull <name>\`.`],

  ['vendor/NOTICE.md', `\`vendor/NOTICE.md\` is generated by \`scripts/vendor-skills.mjs\`.

Every copyright holder and every "no license file is published" callout in it comes from
the manifest. Fix the manifest entry and re-run the pull; a hand-edit is overwritten on the
next one and drops attribution in the meantime.`],

  ['plugins/nt-brand/skills/system/', `\`plugins/nt-brand/skills/system/\` is a byte mirror of the published \`@notambourine/brand-kit\`.

A plugin install runs no npm, so these committed bytes are the runtime. \`npm run brand\`
compares them against the pinned tarball and fails on any drift. Fix it upstream in
\`notambourine/brand-kit\`, release, exact-pin, then \`npm run brand:sync\`.`],
];

const payload = rawPayload();
if (!payload) pass();

const input = payload.tool_input ?? {};
const target = [input.file_path, input.notebook_path, input.path].find((p) => typeof p === 'string' && p);
if (!target) pass();

const rel = repoPath(target);
if (!rel) pass();

for (const [prefix, reason] of FENCED) {
  if (rel === prefix || rel.startsWith(prefix)) deny(reason);
}
pass();

/* The target as a forward-slash path under ROOT, or null when it is somewhere else. */
function repoPath(raw) {
  let path = raw;
  if (path.startsWith('~/')) path = join(process.env.HOME ?? process.env.USERPROFILE ?? '', path.slice(2));
  if (!isAbsolute(path)) path = resolve(payload.cwd || ROOT, path);
  const rel = relative(ROOT, path);
  if (!rel || rel.startsWith('..') || isAbsolute(rel)) return null;
  return rel.split(sep).join('/');
}

/* --- the harness ---------------------------------------------------------- */

/* Node rather than bash, and self-contained rather than importing nt-dev's lib: see
   .claude/rules/portable-shell.md for the first, and a repo hook that breaks when a plugin
   is extracted for the second. */

function pass() {
  process.exit(0);
}

function deny(reason) {
  console.log(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'deny',
      permissionDecisionReason: `[mirror-fence] ${reason}`,
    },
    systemMessage: '\u{1F534} [mirror-fence] refused a hand-edit to a generated mirror',
  }));
  process.exit(0);
}

/* fd 0, not '/dev/stdin': the device node does not exist on Windows. A non-blocking pipe
   answers EAGAIN before the writer has filled it, which is not end-of-input, so that one
   errno retries and every other error gives up. */
function readStdin() {
  if (process.stdin.isTTY) return '';
  for (let attempt = 0; attempt < 200; attempt += 1) {
    try {
      return readFileSync(0, 'utf8');
    } catch (err) {
      if (err.code !== 'EAGAIN') return '';
      /* No synchronous sleep in node, and the read has to stay synchronous: an async one
         would let the script fall off the end and exit before the payload arrived. */
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 10);
    }
  }
  return '';
}

function rawPayload() {
  try {
    return JSON.parse(readStdin());
  } catch {
    return null;
  }
}
